# Generated by Django 2.1.7 on 2019-03-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_admission_is_student'),
        ('Automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=30, verbose_name='UserID')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Automation.Class')),
                ('FormID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Admission')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Automation.Section', verbose_name='Section')),
            ],
        ),
    ]
