# Generated by Django 2.1.7 on 2019-03-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Automation.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='FormID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.Admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Automation.Section', verbose_name='Section'),
        ),
    ]
