# Generated by Django 2.1.7 on 2019-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0003_auto_20190322_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='FormID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=2, verbose_name='Section'),
        ),
    ]
