# Generated by Django 2.1.7 on 2019-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0004_auto_20190322_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(max_length=10),
        ),
    ]
