# Generated by Django 2.1.7 on 2019-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0005_auto_20190322_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='UserID',
            field=models.CharField(max_length=30, unique=True, verbose_name='UserID'),
        ),
    ]
