# Generated by Django 2.1.7 on 2019-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0007_result_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Password',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
