# Generated by Django 2.1.7 on 2019-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0009_auto_20190325_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('phone_no', models.IntegerField(verbose_name='Phone No')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='ResultAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('phone_no', models.IntegerField(verbose_name='Phone No')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('department', models.CharField(max_length=60, verbose_name='Department')),
                ('phone_no', models.IntegerField(verbose_name='Phone No')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
            ],
        ),
    ]
