# Generated by Django 2.1.7 on 2019-03-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0010_admissionofficer_resultadmin_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultAdmin',
            new_name='ResultOfficer',
        ),
    ]
