# Generated by Django 2.1.7 on 2019-03-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='mohers_qualification',
        ),
        migrations.AddField(
            model_name='admission',
            name='mothers_qualification',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Honors', 'Honors'), ('Masters', 'Masters'), ('Others', 'Others')], default='SSC', max_length=100, verbose_name='Mothers (Qualification)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_phone',
            field=models.IntegerField(max_length=12, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='fathers_qualification',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Honors', 'Honors'), ('Masters', 'Masters'), ('Others', 'Others')], default='SSC', max_length=100, verbose_name='Fathers (Qualification)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='last_class',
            field=models.CharField(choices=[('Six', 'VI'), ('Seven', 'VII'), ('Eight', 'VIII'), ('Nine', 'IX'), ('Ten', 'X')], default='VI', max_length=100, verbose_name='Last Class Attended'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='moher_phone',
            field=models.IntegerField(max_length=12, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hinduism'), ('Buddha', 'Buddhaism'), ('Christian', 'Christian'), ('Other', 'Other')], default='Islam', max_length=100, verbose_name='Religion'),
        ),
    ]
