# Generated by Django 2.1.7 on 2019-03-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_admission_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Class',
            field=models.CharField(choices=[('Six', 'VI'), ('Seven', 'VII'), ('Eight', 'VIII'), ('Nine', 'IX'), ('Ten', 'X')], default='VI', max_length=100, verbose_name='Sought Admission in'),
        ),
    ]
